description: |
  Configuration used to load extensions.
type: object
required:
  - $schema
properties:
  $schema:
    type: string
patternProperties:
  "^(action|previewer|processor|renderer|source)$":
    description: |
      Configuration map for the extensions of the kind.
      The key is the name and the value is the configuration.
    type: object
    patternProperties:
      "^[a-zA-Z0-9_\\-]+$":
        $ref: "#/$defs/loaderConfig"
    additionalProperties: false
additionalProperties: false

$defs:
  loaderConfig:
    description: |
      The configuration for loading an extension.
    type: object
    required:
      - uri
    properties:
      uri:
        description: |
          The URI of the extension.
          If the URI starts with 'builtin:', it refers to a built-in extension.
          If the URI starts with 'package:', it refers to a package extension.
          If the URI is relative, it is resolved against the configuration file.
        type: string
      options:
        $ref: "#/$defs/options"
      variants:
        $ref: "#/$defs/variants"
  options:
    description: |
      An options object passed to the extension.
      See the extension's documentation for valid options.
    type: object
  variants:
    description: |
      An object defining variants of the extension.
      The key is the variant name and the value is the options object.
      The variant name is prefixed to the extension name with a colon (:).
    type: object
    patternProperties:
      "^[a-zA-Z0-9_\\-:]+$":
        $ref: "#/$defs/options"
    additionalProperties: false
$schema: "http://json-schema.org/draft-07/schema"
