$schema: 'http://json-schema.org/draft-07/schema'
description: |
  Package registry
type: object
required:
  - $schema
  - $version
properties:
  $schema:
    type: string
  $version:
    const: '1-beta'
  package:
    type: object
    additionalProperties:
      $ref: '#/$defs/package'
additionalProperties: false
$defs:
  package:
    type: object
    properties:
      base:
        description: |
          The base URL for the package.
          All relative URLs in the package are resolved relative to this URL.
          If no base is provided, the base is the URL of the package json file.
        type: string
      action:
        description: |
          Definition map for action extensions.
          The key is the action name and the value is the definition of that action.
        type: object
        additionalProperties:
          $ref: '#/$defs/packageExtension'
      previewer:
        description: |
          Definition map for previewer extensions.
          The key is the previewer name and the value is the definition of that previewer.
        type: object
        additionalProperties:
          $ref: '#/$defs/packageExtension'
      processor:
        description: |
          Definition map for processor extensions. 
          The key is the processor name and the value is the definition of that processor.
        type: object
        additionalProperties:
          $ref: '#/$defs/packageExtension'
      renderer:
        description: |
          Definition map for renderer extensions.
          The key is the renderer name and the value is the definition of that renderer.
        type: object
        additionalProperties:
          $ref: '#/$defs/packageExtension'
      source:
        description: |
          Definition map for source extensions. 
          The key is the source name and the value is the definition of that source.
        type: object
        additionalProperties:
          $ref: '#/$defs/packageExtension'
  packageExtension:
    description: Extension in the package
    type: object
    required:
      - url
    properties:
      url:
        description: |
          The URL of the extension.
          If a relative URL is provided, it is resolved relative to the package's URL.
        type: string
      options:
        $ref: '#/$defs/options'
      variants:
        $ref: '#/$defs/variants'
  options:
    description: |
      An options object passed to the extension.
      See the extension's documentation for valid options.
    type: object
  variants:
    description: |
      An object defining variants of the extension.
      The key is the variant name and the value is the options object.
      The variant name is prefixed to the extension name with a colon (:).
    type: object
    additionalProperties:
      $ref: '#/$defs/options'
